In [93]:
import pandas as pd
# part 1
# 1.a: load data frame from file, store into df
df = pd.read_csv('KNNAlgorithmDataset.csv')
#print(df, type(df))

#1.c: shuffle the samples
df = df.sample(frac=1)  #??? q01: if re-indexing needed? 
# frac = [0,1], incase frac = 0.5, shuffle 50% of the rows
#print(df)

# convert data frame into array
data_array = df.values[:, 1:]  #unselect 1st column / label y
#print(data_array)

# 1.b: set column 'diagnosis' as target variable y / the label
y = df["diagnosis"].values
#print(y) 

In [103]:
# Task 01: normalizing the data with z-score normalization

mean = data_array.mean(axis=0)
standard_deviation = data_array.std(axis=0)

normalized_data = (data_array - mean) / standard_deviation

print(normalized_data)

[[1.097e+01 1.122e+01 2.161e+01 ... 1.919e+01 1.234e+01 1.290e+01]
 [1.720e+01 1.986e+01 2.228e+01 ... 1.594e+01 2.222e+01 1.592e+01]
 [7.173e+01 7.194e+01 1.444e+02 ... 1.263e+02 7.985e+01 8.374e+01]
 ...
 [1.555e-01 2.022e-02 2.422e-01 ... 1.777e-01 8.194e-02 1.012e-01]
 [2.540e-01 3.292e-01 3.828e-01 ... 2.443e-01 2.268e-01 3.549e-01]
 [9.532e-02 6.522e-02 1.007e-01 ... 6.251e-02 9.082e-02 8.118e-02]]


In [ ]:
# Task 01: normalizing the data with z-score normalization
# QN why does data shift 1st column by 1, the rest by 2?


for i in df:
    feature = df[i].values
    feature_mean = feature.mean()
    feature_standard_deviation = feature.std()  
    print(feature)

    for x in feature:
        x = ((x - feature_mean) / feature_standard_deviation)

    #z_Score_Normalization(df[feature])

array = df["perimeter_mean"].values
#z_Score_Normalization(array)
#print(array)
#print(df["perimeter_mean"])


In [10]:
# Task 02: seperate data into training(70%), validation(20%) and test(10%) sets by slicing
da_len = len(data_array)   #number of rows / length of data_array
training_set = data_array[:int(da_len * 0.7)]
#print(training_set)
validation_set = data_array[int(da_len * 0.7): int(da_len * 0.9)]
test_set = data_array[int(da_len* 0.9):]
#print(len(training_set) + len(validation_set) + len(test_set) == da_len) # the whole data array included in the 3 sets: True 

In [11]:
# 3.c distance algorithms with input of two 1D-Vectors, return distance (real number) of 2 vectors
import numpy as np
# Manhattan distance
def manhattan_distance(vector01, vector02):
    # raise error if data points are not of the same length
    if (len(vector01) != len(vector02)):
        raise ValueError("Unequal length of inputed data points")
    # return sum(\xi_m - xj_m\)
    return np.sum(np.abs(vector01 - vector02))    # np.abs(): absolute value of each elements
    # a variante: use np.fabs(v1, v2), return np.sum(np.fabs(vector01 - vector02))

# Euclidean distance
def euclidean_distance(vector01, vector02):
    if (len(vector01) != len(vector02)):
        raise ValueError("Unequal length of inputed data points")
    # use np library: calculate the norm of the new vector (difference of two old vectors)
    return np.linalg.norm(vector01 - vector02)

# Chebyshev distance
def chebyshev_distance(vector01, vector02):
    if (len(vector01) != len(vector02)):
        raise ValueError("Unequal length of inputed data points")
    # return max(\xi_01 - xi_02\)
    absolute_array = [np.abs(vector01[i] - vector02[i]) for i in range(len(vector01))]
    return max(absolute_array)


# test algo with data: 
#t_p01 = training_set
#t_p02 = training_set
#t_short01 = [1.1,2,4.43,8]
#t_short02 = [3,4.7,6,9.69]

#print(manhattan_distance(t_p01, t_p02))    # test (compared with result by online calculator): True
#print(euclidean_distance(t_p01, t_p02))    # definition from numpy library
#print(chebyshev_distance(t_short01, t_short02))    # test: True

In [71]:
# Task 3: implement the kNN algorithm
# accroding to 2.2 kNN algo is capsuled in a kNN predictor
class kNN_predictor:
    #constructor: define attribiutes
    def __init__(self, k, distance_func):    #q: if the k and dist-func is given as param in constructor or later in predict func?
        self.trained = False   #default: not trained
        self.k = k  # k neighbours
        self.d = distance_func
        # X(data set) and Y(classes / target values) will be provided in fit() as parameters
        self.X = None
        self.Y = None
        # something about the classification / regression calculated based on data from training set
        
    # functions
        def fit(self, training_X, training_Y):
            #feed the model with training data
            self.X = training_X
            self.Y = training_Y
            #do something
            self.trained = True   #set trained
            
        def predict(self):
            #predict classification or regression result for new data.
            # check if predictor is trained
            if self.trained == False:
                raise("Predictor is not trained! Train it first by calling fit()!")
            # TODO: call normalize() to normalize the data
            return None
            
        def confusionMatrix(self, X):
            #compute confusion matrix, input: X (user input)
            return None
    
    
  

In [85]:
# task 3.2: check if user inputs are valid
def check_predictor_input(k, d):
    valid_dist_algos = ['manhattan', 'euclidean', 'chebyshev']
    # TODO: not sure about the k value area, len(training_set) = 398
    if k > len(training_set):
        raise ValueError(f"Given k too large! Give a number not larger than {len(training_set)}")
    if d.lower() not in valid_dist_algos:
        raise ValueError(f"Given algorithm is not valid, please choose from {valid_dist_algos}!")
        
#test: passed
#check_predictor_input(100, 'manha')
#check_predictor_input(400, 'chebyshev')

In [78]:
# task 3.3: make an API
class simple_API:
    def __init__(self, k, d):
        # check if k and d are valid
        check_predictor_input(k, d)
        self.k = k
        self.d = d
        
        # create predictor with inputs
        self.predictor = kNN_predictor(k, d)
        
        # train the predictor with training data 
        x = training_set
        y = y[:len(training_set)]   #slice the labels for training set
        # call predictor.fit() with training data
        self.predictor.fit(x, y)
   
    #predict new data
    def predict(self, newdata):
        return self.predictor.predict(#something)
            
    #a func make graphic?

In [ ]:
# Task 4: test the data with user inputs

In [ ]:
# Task 5: visualization