# Numpy 

Fundamental building block of scientific Python.
* Powerful and highly flexible [array class](https://numpy.org/doc/stable/reference/generated/numpy.array.html); your new ubiquitous working unit.
* We will often refer to these objects as $\textit{matrices}$, although this should not be confused with Numpy's less used [matrix class](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html)
* Set of most common mathematical utilities (constants, random numbers, linear algebra functions).

When doing multiple identical mathematical or boolean operations you should prefer numpy `array` objects over build-in python datatypes. Numpy performs operations in an optimized manner. You can get rid of many `while` and `for` loops and obtain fast, scalable and readable code by using `array` objects and the functions provided by `numpy` and `scipy`.

## Import

In [1]:
# imports
import numpy as np                 # It will be used a lot, so the shorthand is helpful.
import matplotlib.pyplot as plt    # Same here.

# ipython magic function to show the plots inline in the notebook
%matplotlib inline

## Numpy array basics

A numpy array is a collections of values all of the same type. A numpy array **cannot** change their size once they are created, but they **can** change their shape, i.e., an array will always hold the same number of elements, but their organization into rows and columns may change as desired.
* **ndarray.ndim:** The number of axes/dimensions of an array. The default matrix used for math problems is of dimensionality 2.
* **ndarray.shape:** A tuple of integers indicating the size of an array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim. 
* **ndarray.size:** The total number of elements of the array. This is equal to the product of the elements of shape. 
* **ndarray.dtype:** The data type of the array elements. Defaults to the type of the elements in the array can be set when the array is created.

(*see:* [Numpy basics](https://docs.scipy.org/doc/numpy/user/quickstart.html) )

In [ ]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]], dtype=np.int32) # np.float32, np.float64, np.complex64, np.complex128
print(m)
print(m.dtype)
print(m.shape)

### Under the hood
Numpy arrays believe in sharing is caring and will share their data with other arrays. Slicing does NOT return a new array, but instead a *view* on the data of the same array (except when the slice returns a scalar):

In [ ]:
s = m[1]
print('BEFORE')
print(s, 'slice', '\n')
print(m, '\n')
s[0] = 0
print('AFTER')
print(s, 'slice' '\n')
print(m, '\n')

You can check whether an array actually owns its data by looking at its flags:

In [ ]:
print(m.flags)
print(s.flags)

## Array creation

In [ ]:
# helper function for examples below; plots the graphical depiction of a given numpy array
def show_matrix(X):
    Y = np.array(np.array(X, ndmin=2))  # 1D -> 2D
    vmin = min(np.min(Y), 0)
    vmax = max(np.max(Y), 1)
    fig, ax = plt.subplots(figsize=(4, 3))
    img = ax.imshow(Y, interpolation='none', vmin=vmin, vmax=vmax)
    fig.colorbar(img)
    print(X)

In [ ]:
Z = np.zeros(9)
show_matrix(Z)

In [ ]:
Z = np.zeros((5,9))
show_matrix(Z)

In [ ]:
Z = np.ones(9)
show_matrix(Z)

In [ ]:
Z = np.ones((5,9))
show_matrix(Z)

In [ ]:
Z = np.array( [0,0,0,0,0,0,0,0,0] )
show_matrix(Z)

In [ ]:
Z = np.array( [[0,0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0,0]] )
show_matrix(Z)

In [ ]:
Z = np.arange(9)    # the numpy arange function also allows floating point arguments
show_matrix(Z)

(*see also:* [linspace](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html))

In [ ]:
Z = np.arange(5*9).reshape(5,9)
show_matrix(Z)

- Reshape must not change the total number of elements in the array.
- A vector of length ***n*** and a matrix of dimensions (1,***n***) ARE NOT THE SAME THING!

In [ ]:
Z = np.random.uniform(0,1,9)  # args: min, max, no. of elements
show_matrix(Z)

In [ ]:
Z = np.random.uniform(0, 1, (5, 9))
show_matrix(Z)

(*see:* [Numpy array creation](https://docs.scipy.org/doc/numpy/user/basics.creation.html) & [Numpy array reshaping](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html))

## Array indexing

In [ ]:
# single element
Z = np.zeros((5, 9))
Z[1,1] = 1
show_matrix(Z)

In [ ]:
# single row
Z = np.zeros((5, 9))
Z[1,:] = 1
show_matrix(Z)

In [ ]:
# single column
Z = np.zeros((5, 9))
Z[:,1] = 1
show_matrix(Z)

In [ ]:
# specific area
Z = np.zeros((5, 9))
Z[2:4,2:6] = 1            # for each dimension format is always: <from:to:step> (with step being optional)
show_matrix(Z)

In [ ]:
# every second column
Z = np.zeros((5, 9))
Z[:,::2] = 1              # for each dimension format is always: <from:to:step> (with step being optional)
show_matrix(Z)

In [ ]:
# indices can be negative
Z = np.arange(10)
print(">>> Z[-1]:  ", Z[-1])       # start indexing at the back
print(">>> Z[3:-3]:", Z[3:-3])     # slice of array center
print(">>> Z[::-1]:", Z[::-1])     # quickly reverse an array

(*see:* [Numpy array slicing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html))

# Multiplication of arrays

Numpy offers many ways to multiply arrays. If we use python's `*` operator, this performs elementwise multiplication. In the case of 1D arrays of equal size, this can be used as an initial step in calculating the Euclidean inner product:

In [ ]:
x=np.array([2,7,8])
y=np.array([5,2,7])
star=x*y
print(star)
inner=np.sum(star)
print(inner)

However, if we wanted to work out this inner product, Numpy also offers `np.inner()` which is more compact:

In [ ]:
np.inner(x,y)

For 2D arrays, elementwise multiplication not a common operation. Instead, we are often interested in performing matrix multiplication. Numpy offers different ways to do this. One option is to use `np.dot()`, although due to it's name being related to another operation in linear algebra, we instead recommond `np.matmul()`:

In [ ]:
x=np.array([[1,3],
           [2,4]])
y=np.array([[1,2],
           [2,1]])
np.matmul(x,y)

`np.matmul()` also has the possibility to use the symbol `@` as a shorthand. It should be noted that the use of this symbol is not fully pythonic ([see here](https://blog.finxter.com/numpy-matmul-operator/)). However, it can make chains of matrix multiplication very compact, and therefore can such computations very readable and transparent. For example:

In [ ]:
x@y@y@x@y@x #long chain of matrices multiplied together

For arrays with more than two dimensions, `np.matmul()` and `np.dot()` provide [different outputs](https://www.delftstack.com/howto/numpy/numpy-dot-vs-matmul/)

## Broadcasting

Arithmetic operations applied to two Numpy arrays of different dimensions leads to 'broadcasting', i.e., making the shapes compatible to allow the operation if possible (*see:* [Numpy broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) for more details). This includes:

* Adding/subtracting/etc. a single value to a matrix.

In [22]:
x = np.arange(1,10,1)
x += 2
print(x)

[ 3  4  5  6  7  8  9 10 11]


* Adding/subtracting/etc. a column/row vector to a matrix.

In [23]:
x = np.arange(4*3).reshape(4,3)
y = np.arange(10,13,1)
print(x)
print(y)
print(x+y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[10 11 12]
[[10 12 14]
 [13 15 17]
 [16 18 20]
 [19 21 23]]


* Adding/subtracting/etc. a column and a row vector.

In [24]:
x = np.arange(8)
y = x.reshape(1,8)
print(x+y)

[[ 0  2  4  6  8 10 12 14]]


* Elementwise multiplication of arrays with different shapes or dimensionalities. When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when: i) they are equal, or ii) one of them is 1. If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the size that is not 1 along each axis of the inputs.

In [38]:
#One dimension matching and one dimension in second array with size 1 -> okay
arr1=np.random.randint(1,10, size=(4,5))
arr2=np.random.randint(1,10, size=(1,5))
print(arr1*arr2)

[[16  3 42 32 10]
 [14  3 42 40 14]
 [ 2 27 36 48 18]
 [ 2 12 54 72  2]]


In [39]:
#Both dimensions in second array with size 1 -> okay
arr1=np.random.randint(1,10, size=(4,5))
arr2=np.array([[5]])
print(arr1*arr2)

[[25 40 15 40 35]
 [45 40 10 45 15]
 [45 25 10 45 35]
 [10 45 25 40 30]]


In [40]:
#First array has more dimensions than second but trailing dimensions obey both rules
arr1=np.random.randint(1,100, size=(3,5,4,2,6,3))
arr2=np.random.randint(1,100, size=(4,1,6,1))
y=arr1*arr2
print(y.shape)

(3, 5, 4, 2, 6, 3)


In [32]:
#Arrays have an inconsistent dimension
arr1=np.random.randint(1,20, size=(4,3))
arr2=np.random.randint(1,20, size=(4,5))
print(arr1*arr2)

ValueError: operands could not be broadcast together with shapes (4,3) (4,5) 

# Matrix computations

Numpy's [linalg library](https://numpy.org/doc/stable/reference/routines.linalg.html) provides a number of useful matrix and vector operations from linear algebra, which are often useful in many domains of scientific computing. In particular, when dealing with square arrays, one can make use of the eigevalue solver as well as matrix inversion.

In [ ]:
#Eigenvalues and vectors
arr_sym = np.array([[1,2],
                  [2,1]]) #symmetric matrix

vals, vecs = np.linalg.eig(arr_sym)
print("Eigenvalues:\n", vals) #eigenvalues stored as a 1D array
print("Eigenvectors:\n", vecs) #eigenvectors stored as columns in a 2D array

In [ ]:
#Matrix inversion
np.linalg.inv(arr_sym)

## Exercises
1. Generate a 5x9 matrix of random integers between 0 and 10.
2. Select a tile-pattern subset of the matrix like this (the resulting matrix can either has reduced shape based on the subset, or it can keep a shape of 5x9):
![Tile pattern](http://i.imgur.com/Cs7N10t.png)
3. ..and like this:
![Tile pattern](http://i.imgur.com/BnGdHle.png)
4. ..and also like this:
![Tile pattern](http://i.imgur.com/i3Lw1Zb.png)
5. Adapt the code for No.3 so that it works with matrices of arbitrary dimensions (if it does not already).
6. Write a function code that perfoms the operation depicted below ([source](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)), i.e. for two arrays with shape (a,1) and (b,1) the result should have shape (a,b).
![Broadcast op](http://i.imgur.com/M3kL9we.png)

7. Make a copy of your matrix from No. 6
8. Find an expression that subtracts the mean of all rows from every row of any given matrix, the shorter the better (one-line is possible). Try the code with the copied matrix.
9. In the matrix from No. 6: 
    1. Reverse the order of the rows of the matrix using a single slice.
    2. Reverse the order of the columns of the matrix using a single slice.
    3. Reverse the order of both the rows and the columns of the matrix using a single slice.
    4. Try evaluation a standard Python conditional on your matrix (e.g. $> 5$). Describe the result in one sentence.
    5. Find an expression that checks if ANY value is larger than 7 using numpy's "any"-function.
    6. Find an expression that checks if ALL values are larger than 2 using numpy's "all"-function.
    7. Use a conditional and boolean/mask indexing to index all even values of your matrix.  
    8. Increment even values by 1.
10. Use numpy's "linspace" function to create a vector of 50 numbers between $-3\pi$ and $3\pi$ in evenly spaced increments.
    1. Display it with the showMatrix function.
    2. Apply a sine function to the vector and display the result, also with the showMatrix function.
    3. Apply a square function to the (original) vector and display the result, also with the showMatrix function.
    

In [ ]:
# Your code